### Reading images into python

- Two primary libraries for reading images are scikit-image and opencv
- Pillow (PIL) can also be used
- However, it does not import images as numpy arrays; it imports the image as an object
- You can convert it into a numpy array using numpy.asarray(image_path)

In [1]:
from skimage import io

In [2]:
img = io.imread(r"D:\ML & DL\IP@SP\image folder\stars.jpg")

In [3]:
print(img.shape)

(4000, 6000, 3)


In [4]:
print(img.dtype)

uint8


- (y, x, c)
- (4000 pixels in height of image, 6000 pixels in width of image, RGB channels)
- unsigned integers going from 0 to 255

In [6]:
print(img[0][1][2])
print(img[3000][5000][1])

9
8


- WAFP to read all the images in image folder and print their size

In [7]:
from skimage import img_as_float

In [8]:
img2 = img_as_float(img)

In [9]:
print(img2.shape)

(4000, 6000, 3)


In [10]:
print(img2.dtype)

float64


In [11]:
print(img2[0][1][2])
print(img2[3000][5000][1])

0.03529411764705882
0.03137254901960784


- Everything remains the same, only the values are scaled between 0 and 1
- Ensures each pixel has a similar data distribution making convergence faster during training

- WAFP to normalize all the images in image folder

In [12]:
import numpy as np

In [14]:
img3 = img.astype(np.float64)

In [15]:
print(img3.shape)

(4000, 6000, 3)


In [16]:
print(img3.dtype)

float64


In [17]:
print(img3[0][1][2])
print(img3[3000][5000][1])

9.0
8.0


- Values are float but not scaled between 0.0 and 1.0
- Do not do this

In [18]:
from skimage import img_as_ubyte

In [19]:
img_8bit = img_as_ubyte(img2)

In [20]:
print(img_8bit.shape)

(4000, 6000, 3)


In [21]:
print(img_8bit.dtype)

uint8


In [22]:
print(img_8bit[0][1][2])
print(img_8bit[3000][5000][1])

9
8


- Converting it back to original form
- Image --> Normalize --> Process the image --> Convert back --> Save it

In [7]:
import cv2

In [26]:
img_cv2 = cv2.imread(r"D:\ML & DL\IP@SP\image folder\stars.jpg")

In [27]:
print(img_cv2)

[[[ 9  4  6]
  [ 9  4  6]
  [ 9  4  6]
  ...
  [ 9  4  6]
  [ 9  4  6]
  [ 9  4  6]]

 [[ 9  4  6]
  [ 9  4  6]
  [ 9  4  6]
  ...
  [ 9  4  6]
  [ 9  4  6]
  [ 9  4  6]]

 [[ 9  4  6]
  [ 9  4  6]
  [ 9  4  6]
  ...
  [ 9  4  6]
  [ 9  4  6]
  [ 9  4  6]]

 ...

 [[47  0 16]
  [48  1 17]
  [48  1 17]
  ...
  [32  1 10]
  [31  0  9]
  [30  0  8]]

 [[47  0 16]
  [48  1 17]
  [48  1 17]
  ...
  [33  2 11]
  [32  1 10]
  [31  0  9]]

 [[48  1 17]
  [48  1 17]
  [48  1 17]
  ...
  [34  3 12]
  [32  1 10]
  [32  1 10]]]


In [28]:
print(img)

[[[ 6  4  9]
  [ 6  4  9]
  [ 6  4  9]
  ...
  [ 6  4  9]
  [ 6  4  9]
  [ 6  4  9]]

 [[ 6  4  9]
  [ 6  4  9]
  [ 6  4  9]
  ...
  [ 6  4  9]
  [ 6  4  9]
  [ 6  4  9]]

 [[ 6  4  9]
  [ 6  4  9]
  [ 6  4  9]
  ...
  [ 6  4  9]
  [ 6  4  9]
  [ 6  4  9]]

 ...

 [[16  0 47]
  [17  1 48]
  [17  1 48]
  ...
  [10  1 32]
  [ 9  0 31]
  [ 8  0 30]]

 [[16  0 47]
  [17  1 48]
  [17  1 48]
  ...
  [11  2 33]
  [10  1 32]
  [ 9  0 31]]

 [[17  1 48]
  [17  1 48]
  [17  1 48]
  ...
  [12  3 34]
  [10  1 32]
  [10  1 32]]]


- opencv reads images as BGR
- Central channel remains the same
- Red and Blue channels have been swapped

In [30]:
print(img_cv2.shape)
print(img.shape)

(4000, 6000, 3)
(4000, 6000, 3)


In [31]:
print(img_cv2.dtype)
print(img.dtype)

uint8
uint8


In [32]:
img_cameraman = cv2.imread(r"D:\ML & DL\IP@SP\image folder\cameraman.png")

In [33]:
img_cameraman.shape

(490, 487, 3)

In [35]:
img_cameraman[0]

array([[249, 249, 249],
       [251, 251, 251],
       [251, 251, 251],
       ...,
       [253, 253, 253],
       [251, 251, 251],
       [253, 253, 253]], dtype=uint8)

In [36]:
img2_cameraman = io.imread(r"D:\ML & DL\IP@SP\image folder\cameraman.png")

In [37]:
img2_cameraman.shape

(490, 487)

In [38]:
img2_cameraman[0]

array([249, 251, 251, 253, 255, 255, 253, 253, 251, 253, 253, 255, 255,
       255, 255, 253, 253, 253, 253, 253, 253, 253, 255, 255, 253, 255,
       255, 253, 253, 253, 255, 255, 253, 255, 255, 255, 253, 253, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 253, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 253, 253, 253, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 253, 253, 253, 253,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 251, 251, 253, 253, 253, 255, 255, 255, 255, 255,
       253, 253, 255, 255, 255, 255, 253, 253, 253, 253, 253, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 253, 255, 255, 255, 25

In [42]:
img_cameraman_grey = cv2.imread(r"D:\ML & DL\IP@SP\image folder\cameraman.png", 0)

- Use 0 flag to read the image as greyscale
- Use 1 flag to read the image with colour channels

- WAFP to check whether a JPEG image is coloured or grayscale; use the demo file in image folder to test your results

In [43]:
img_cv2_RGB = cv2.cvtColor(img_cv2, cv2.COLOR_BGR2RGB)

In [44]:
print(img_cv2_RGB)

[[[ 6  4  9]
  [ 6  4  9]
  [ 6  4  9]
  ...
  [ 6  4  9]
  [ 6  4  9]
  [ 6  4  9]]

 [[ 6  4  9]
  [ 6  4  9]
  [ 6  4  9]
  ...
  [ 6  4  9]
  [ 6  4  9]
  [ 6  4  9]]

 [[ 6  4  9]
  [ 6  4  9]
  [ 6  4  9]
  ...
  [ 6  4  9]
  [ 6  4  9]
  [ 6  4  9]]

 ...

 [[16  0 47]
  [17  1 48]
  [17  1 48]
  ...
  [10  1 32]
  [ 9  0 31]
  [ 8  0 30]]

 [[16  0 47]
  [17  1 48]
  [17  1 48]
  ...
  [11  2 33]
  [10  1 32]
  [ 9  0 31]]

 [[17  1 48]
  [17  1 48]
  [17  1 48]
  ...
  [12  3 34]
  [10  1 32]
  [10  1 32]]]


- Use skimage and cv2 to read images
- Both open images as numpy arrays, meaning that the images are ready to be processed

In [2]:
img_pens = io.imread(r"D:\ML & DL\IP@SP\image folder\pens.bmp")
img_pens.shape

(480, 512, 3)

In [3]:
img_pens.max()

255

In [4]:
img_pens.min()

0

In [61]:
img_pens = img_pens * 0.5

In [62]:
img_pens.max()

127.0

In [63]:
img_pens.min()

0.0

In [68]:
io.imsave("saved images/scaled_pens.jpg", img_pens)

Lossy conversion from float64 to uint8. Range [0.0, 127.0]. Convert image to uint8 prior to saving to suppress this warning.


In [69]:
from skimage import filters

In [72]:
img_chestxray = io.imread(r"D:\ML & DL\IP@SP\image folder\chestxray.jpg")
img_chestxray.shape

(1600, 1600)

In [73]:
gaussian_img = filters.gaussian(img_chestxray, sigma=2)
io.imsave("saved images/chestxray@gaussian.jpg", gaussian_img)

Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.


In [74]:
from skimage import img_as_ubyte
gaussian_img_8bit = img_as_ubyte(gaussian_img)

In [76]:
io.imsave("saved images/chestxray@gaussian2.jpg", gaussian_img_8bit)

In [77]:
cv2.imwrite("saved images/chestxray@gaussian3.jpg", gaussian_img_8bit)

True